# Generated by Django 5.0.6 on 2026-09-21 08:17

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vendors", "0038_vendoroperationalattributes"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorAnalysisSection",
            fields=[],
            options={
                "verbose_name": "Fornitore",
                "verbose_name_plural": "Vendors - Analysis and Classification",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("vendors.vendor",),
        ),
    ]
