# Generated by Django 6.0.8 on 2026-09-18 10:32

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vendors", "0038_vendoroperationalattributes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[],
            options={
                "verbose_name": "Servizio",
                "verbose_name_plural": "Registro Servizi",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("vendors.vendorservice",),
        ),
        migrations.CreateModel(
            name="ServiceCatalog",
            fields=[],
            options={
                "verbose_name": "Tipologia di Servizio",
                "verbose_name_plural": "Catalogo Tipologie e Servizi",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("vendors.servicetype",),
        ),
        migrations.CreateModel(
            name="ServiceSet",
            fields=[],
            options={
                "verbose_name": "Set Servizi",
                "verbose_name_plural": "Set Servizi",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("vendors.serviceset",),
        ),
    ]
