# Generated by Django 5.0.6 on 2026-09-24 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={
                "verbose_name": "Servizio Erogato",
                "verbose_name_plural": "Registro Servizi Erogati",
            },
        ),
        migrations.AlterModelOptions(
            name="servicecatalog",
            options={
                "verbose_name": "Tipologia di Servizio Erogato",
                "verbose_name_plural": "Catalogo Tipologie e Servizi Erogati",
            },
        ),
        migrations.AlterModelOptions(
            name="serviceset",
            options={
                "verbose_name": "Set Servizi Erogati",
                "verbose_name_plural": "Set Servizi Erogati",
            },
        ),
    ]
