# Generated by Django 5.0.6 on 2026-09-16 09:11

from django.db import migrations

import vendor_management_system.users.managers


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_is_ldap_user"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                (
                    "objects",
                    vendor_management_system.users.managers.UserManager(),
                ),
            ],
        ),
    ]
