# Generated by Django 6.0.8 on 2026-09-18 10:32

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vendors", "0038_vendoroperationalattributes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competence",
            fields=[],
            options={
                "verbose_name": "Requisito professionale assegnato",
                "verbose_name_plural": "Registro Requisiti professionali",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("vendors.vendorcompetence",),
        ),
        migrations.CreateModel(
            name="CompetenceCatalog",
            fields=[],
            options={
                "verbose_name": "Requisito professionale",
                "verbose_name_plural": "Catalogo Requisiti Professionali",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("vendors.competence",),
        ),
        migrations.CreateModel(
            name="CompetenceSet",
            fields=[],
            options={
                "verbose_name": "Set Requisiti Professionali",
                "verbose_name_plural": "Set Requisiti Professionali",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("vendors.competenceset",),
        ),
    ]
