# Generated by Django 5.0.6 on 2026-09-24 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("competences", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="competence",
            options={
                "verbose_name": (
                    "Abilitazione/Requisito professionale assegnato"
                ),
                "verbose_name_plural": (
                    "Registro Abilitazioni e Requisiti Professionali"
                ),
            },
        ),
        migrations.AlterModelOptions(
            name="competencecatalog",
            options={
                "verbose_name": "Abilitazione/Requisito professionale",
                "verbose_name_plural": (
                    "Catalogo Abilitazioni e Requisiti Professionali"
                ),
            },
        ),
        migrations.AlterModelOptions(
            name="competenceset",
            options={
                "verbose_name": ("Set Abilitazioni e Requisiti Professionali"),
                "verbose_name_plural": (
                    "Set Abilitazioni e Requisiti Professionali"
                ),
            },
        ),
    ]
