# Generated by Django 5.0.6 on 2025-10-15 20:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPerformance',
            fields=[
                ('id', models.CharField(editable=False, help_text='Unique ID for Historical Performance Record', max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='ID must be uppercase alphanumeric', regex='^[A-Z0-9]+$')], verbose_name='Historical Performance Record ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date of Historical Performance Record', verbose_name='Date')),
                ('on_time_delivery_rate', models.FloatField(blank=True, help_text='On-time Delivery Rate of Vendor', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='On-time Delivery Rate')),
                ('quality_rating_avg', models.FloatField(blank=True, help_text='Quality Rating Average of Vendor', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Quality Rating Average')),
                ('average_response_time', models.FloatField(blank=True, help_text='Average Response Time of Vendor', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Average Response Time')),
                ('fulfillment_rate', models.FloatField(blank=True, help_text='Fulfillment Rate of Vendor', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Fulfillment Rate')),
                ('vendor', models.ForeignKey(help_text='Vendor associated with Purchase Order', on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Historical Performance',
                'verbose_name_plural': 'Historical Performances',
                'ordering': ['-date'],
            },
        ),
    ]
