#!/bin/bash

# Set errexit to exit immediately if a command exits with a non-zero status
set -o errexit

# Set pipefail to cause a pipeline to return a failure status if any command in the pipeline fails
set -o pipefail

# Set nounset to exit if an unset variable is referenced
set -o nounset


# Set the Celery broker URL using the REDIS_URL environment variable
# N.B. If only .env files supported variable expansion...
export CELERY_BROKER_URL="${REDIS_URL}"


# Use Python to wait for MySQL to become available before proceeding.
# Connection details come from the DB_* variables consumed by config/settings.py.
python << END
import sys
import time

import MySQLdb

suggest_unrecoverable_after = 30
start = time.time()

while True:
    try:
        MySQLdb.connect(
            db="${DB_NAME}",
            user="${DB_USER}",
            passwd="${DB_PASSWORD}",
            host="${DB_HOST}",
            port=int("${DB_PORT}"),
        )
        break
    except MySQLdb.OperationalError as error:
        sys.stderr.write("Waiting for MySQL to become available...\n")

        if time.time() - start > suggest_unrecoverable_after:
            sys.stderr.write("  This is taking longer than expected. The following exception may be indicative of an unrecoverable error: '{}'\n".format(error))

    time.sleep(1)
END


# Inform that MySQL is available
>&2 echo 'MySQL is available'


# Execute the provided command
exec "$@"
