# Generated by Django 5.0.6 on 2025-10-15 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_code', models.CharField(editable=False, help_text='Unique code for Vendor', max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Vendor Code must be uppercase alphanumeric', regex='^[A-Z0-9]+$')], verbose_name='Vendor Code')),
                ('name', models.CharField(help_text='Name of Vendor', max_length=255, verbose_name='Name of Vendor')),
                ('contact_details', models.TextField(help_text='Contact Details of Vendor', verbose_name='Contact Details of Vendor')),
                ('address', models.TextField(help_text='Address of Vendor', verbose_name='Address of Vendor')),
                ('on_time_delivery_rate', models.FloatField(blank=True, help_text='On-time Delivery Rate of Vendor', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='On-time Delivery Rate')),
                ('quality_rating_avg', models.FloatField(blank=True, help_text='Quality Rating Average of Vendor', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Quality Rating Average')),
                ('average_response_time', models.FloatField(blank=True, help_text='Average Response Time of Vendor in Hours', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Average Response Time')),
                ('fulfillment_rate', models.FloatField(blank=True, help_text='Fulfillment Rate of Vendor', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Fulfillment Rate')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['name'],
            },
        ),
    ]
