# Generated by Django 5.0.6 on 2025-10-17 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='category',
            field=models.CharField(blank=True, help_text="Categoria merceologica (es. 'Servizi', 'Forniture', 'Manutenzione')", max_length=100, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='country',
            field=models.CharField(blank=True, default='Italia', help_text='Paese sede legale', max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, help_text='Email principale', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='fiscal_code',
            field=models.CharField(blank=True, help_text='Codice fiscale', max_length=16, null=True, verbose_name='Fiscal Code'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='iso_certifications',
            field=models.TextField(blank=True, help_text='Elenco delle certificazioni ISO possedute', null=True, verbose_name='ISO Certifications'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='last_audit_date',
            field=models.DateField(blank=True, help_text='Ultimo audit condotto', null=True, verbose_name='Last Audit Date'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='next_audit_due',
            field=models.DateField(blank=True, help_text='Prossima data audit prevista', null=True, verbose_name='Next Audit Due'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, help_text='Telefono di riferimento', max_length=20, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='qualification_date',
            field=models.DateField(blank=True, help_text='Data di qualifica o revisione', null=True, verbose_name='Qualification Date'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='qualification_expiry',
            field=models.DateField(blank=True, help_text='Scadenza della qualifica (es. ogni 12 mesi)', null=True, verbose_name='Qualification Expiry'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='qualification_score',
            field=models.FloatField(blank=True, help_text='Punteggio medio di qualifica (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Qualification Score'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='qualification_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'In attesa'), ('APPROVED', 'Approvato'), ('REJECTED', 'Respinto')], default='PENDING', help_text='Stato della qualifica del fornitore', max_length=20, null=True, verbose_name='Qualification Status'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='reference_contact',
            field=models.CharField(blank=True, help_text='Riferimento principale', max_length=100, null=True, verbose_name='Reference Contact'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='review_notes',
            field=models.TextField(blank=True, help_text='Note di revisione e valutazione', null=True, verbose_name='Review Notes'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('LOW', 'Basso'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto')], default='MEDIUM', help_text='Valutazione del rischio fornitore', max_length=20, null=True, verbose_name='Risk Level'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vat_number',
            field=models.CharField(blank=True, help_text='Partita IVA', max_length=20, null=True, verbose_name='VAT Number'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='website',
            field=models.URLField(blank=True, help_text='Sito web aziendale', null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.TextField(blank=True, help_text='Indirizzo del fornitore', verbose_name='Address of Vendor'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='average_response_time',
            field=models.FloatField(blank=True, help_text='Tempo di Risposta Medio del Fornitore in Ore', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Average Response Time'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact_details',
            field=models.TextField(blank=True, help_text='Dettagli di contatto del fornitore', verbose_name='Contact Details of Vendor'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='fulfillment_rate',
            field=models.FloatField(blank=True, help_text='Rating di Adempimento del Fornitore', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Fulfillment Rate'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(blank=True, help_text='Nome del fornitore', max_length=255, verbose_name='Name of Vendor'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='on_time_delivery_rate',
            field=models.FloatField(blank=True, help_text='Rating di Consegna Puntuale del Fornitore', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='On-time Delivery Rate'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='quality_rating_avg',
            field=models.FloatField(blank=True, help_text='Rating Medio di Qualità del Fornitore', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Quality Rating Average'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(editable=False, help_text='Codice univoco del fornitore', max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Il codice fornitore deve essere alfanumerico maiuscolo', regex='^[A-Z0-9]+$')], verbose_name='Vendor Code'),
        ),
    ]
