# Generated by Django 5.0.6 on 2025-10-17 14:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_category_vendor_country_vendor_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street_address', models.CharField(help_text='Via, numero civico', max_length=255, verbose_name='Street Address')),
                ('street_address_2', models.CharField(blank=True, help_text='Appartamento, scala, interno (opzionale)', max_length=255, null=True, verbose_name='Street Address 2')),
                ('city', models.CharField(help_text='Città', max_length=100, verbose_name='City')),
                ('state_province', models.CharField(blank=True, help_text='Provincia/Stato', max_length=100, null=True, verbose_name='State/Province')),
                ('postal_code', models.CharField(help_text='Codice postale/CAP', max_length=20, verbose_name='Postal Code')),
                ('country', models.CharField(default='Italia', help_text='Paese', max_length=100, verbose_name='Country')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='Latitudine (opzionale)', max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='Longitudine (opzionale)', max_digits=11, null=True, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('address_type', models.CharField(choices=[('LEGAL', 'Sede legale'), ('OPERATIONAL', 'Sede operativa'), ('BILLING', 'Indirizzo fatturazione'), ('SHIPPING', 'Indirizzo spedizione'), ('OTHER', 'Altro')], default='LEGAL', help_text='Tipo di indirizzo', max_length=50, verbose_name='Address Type')),
                ('is_active', models.BooleanField(default=True, help_text='Indirizzo attivo', verbose_name='Is Active')),
                ('notes', models.TextField(blank=True, help_text="Note aggiuntive sull'indirizzo", null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['city', 'country'], name='vendors_add_city_b0a216_idx'), models.Index(fields=['postal_code'], name='vendors_add_postal__ca9847_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Codice univoco della categoria (es. 'SERV', 'FORN', 'MANU')", max_length=20, unique=True, verbose_name='Category Code')),
                ('name', models.CharField(help_text='Nome della categoria', max_length=100, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, help_text='Descrizione dettagliata della categoria', null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Categoria attiva e utilizzabile', verbose_name='Is Active')),
                ('sort_order', models.PositiveIntegerField(default=100, help_text='Ordine di visualizzazione', verbose_name='Sort Order')),
                ('color_code', models.CharField(blank=True, help_text='Codice colore esadecimale (es. #FF5733)', max_length=7, null=True, verbose_name='Color Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('requires_certification', models.BooleanField(default=False, help_text='Categoria che richiede certificazioni specifiche', verbose_name='Requires Certification')),
                ('default_risk_level', models.CharField(choices=[('LOW', 'Basso'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto')], default='MEDIUM', help_text='Livello di rischio di default per questa categoria', max_length=20, verbose_name='Default Risk Level')),
                ('parent', models.ForeignKey(blank=True, help_text='Categoria padre per struttura gerarchica', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='vendors.category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='vendor',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Categoria merceologica del fornitore', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='vendors.category', verbose_name='Category'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['code'], name='vendors_cat_code_d8046a_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'sort_order'], name='vendors_cat_is_acti_c4c35a_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='vendors_cat_parent__703747_idx'),
        ),
    ]
