# Generated by Django 5.0.6 on 2025-10-17 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_address_category_alter_vendor_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Indirizzo del fornitore', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='vendors.address', verbose_name='Address'),
        ),
    ]
