# Generated by Django 5.0.6 on 2025-10-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_alter_vendor_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Fornitore attivo', verbose_name='Is Active'),
        ),
    ]
