# Generated by Django 5.0.6 on 2025-11-04 18:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendor_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-created_at'], 'verbose_name': 'Indirizzo', 'verbose_name_plural': 'Indirizzi'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorie'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name'], 'verbose_name': 'Fornitore', 'verbose_name_plural': 'Fornitori'},
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('LEGAL', 'Sede legale'), ('OPERATIONAL', 'Sede operativa'), ('BILLING', 'Indirizzo fatturazione'), ('SHIPPING', 'Indirizzo spedizione'), ('OTHER', 'Altro')], default='LEGAL', help_text='Tipo di indirizzo', max_length=50, verbose_name='Tipo Indirizzo'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(help_text='Città', max_length=100, verbose_name='Città'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='Italia', help_text='Paese', max_length=100, verbose_name='Paese'),
        ),
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creato il'),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indirizzo attivo', verbose_name='È Attivo'),
        ),
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Latitudine (opzionale)', max_digits=10, null=True, verbose_name='Latitudine'),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Longitudine (opzionale)', max_digits=11, null=True, verbose_name='Longitudine'),
        ),
        migrations.AlterField(
            model_name='address',
            name='notes',
            field=models.TextField(blank=True, help_text="Note aggiuntive sull'indirizzo", null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(help_text='Codice postale/CAP', max_length=20, verbose_name='Codice Postale'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state_province',
            field=models.CharField(blank=True, help_text='Provincia/Stato', max_length=100, null=True, verbose_name='Stato/Provincia'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address',
            field=models.CharField(help_text='Via, numero civico', max_length=255, verbose_name='Indirizzo Strada'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address_2',
            field=models.CharField(blank=True, help_text='Appartamento, scala, interno (opzionale)', max_length=255, null=True, verbose_name='Indirizzo Strada 2'),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aggiornato il'),
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(help_text="Codice univoco della categoria (es. 'SERV', 'FORN', 'MANU')", max_length=20, unique=True, verbose_name='Codice Categoria'),
        ),
        migrations.AlterField(
            model_name='category',
            name='color_code',
            field=models.CharField(blank=True, help_text='Codice colore esadecimale (es. #FF5733)', max_length=7, null=True, verbose_name='Codice Colore'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creato il'),
        ),
        migrations.AlterField(
            model_name='category',
            name='default_risk_level',
            field=models.CharField(choices=[('LOW', 'Basso'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto')], default='MEDIUM', help_text='Livello di rischio di default per questa categoria', max_length=20, verbose_name='Livello di Rischio Predefinito'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Descrizione dettagliata della categoria', null=True, verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Categoria attiva e utilizzabile', verbose_name='È Attiva'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Nome della categoria', max_length=100, verbose_name='Nome Categoria'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Categoria padre per struttura gerarchica', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='vendors.category', verbose_name='Categoria Padre'),
        ),
        migrations.AlterField(
            model_name='category',
            name='requires_certification',
            field=models.BooleanField(default=False, help_text='Categoria che richiede certificazioni specifiche', verbose_name='Richiede Certificazione'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=100, help_text='Ordine di visualizzazione', verbose_name='Ordine di Ordinamento'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aggiornato il'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Indirizzo del fornitore', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='vendors.address', verbose_name='Indirizzo'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='average_response_time',
            field=models.FloatField(blank=True, help_text='Tempo di Risposta Medio del Fornitore in Ore', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tempo di Risposta Medio'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Categoria merceologica del fornitore', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='vendors.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact_details',
            field=models.TextField(blank=True, help_text='Dettagli di contatto del fornitore', verbose_name='Dettagli di Contatto del Fornitore'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='country',
            field=models.CharField(blank=True, default='Italia', help_text='Paese sede legale', max_length=100, null=True, verbose_name='Paese'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='fiscal_code',
            field=models.CharField(blank=True, help_text='Codice fiscale', max_length=16, null=True, verbose_name='Codice Fiscale'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='fulfillment_rate',
            field=models.FloatField(blank=True, help_text='Rating di Adempimento del Fornitore', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tasso di Adempimento'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Fornitore attivo', verbose_name='È Attivo'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='iso_certifications',
            field=models.TextField(blank=True, help_text='Elenco delle certificazioni ISO possedute', null=True, verbose_name='Certificazioni ISO'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='last_audit_date',
            field=models.DateField(blank=True, help_text='Ultimo audit condotto', null=True, verbose_name='Data Ultimo Audit'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(blank=True, help_text='Nome del fornitore', max_length=255, verbose_name='Nome del Fornitore'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='next_audit_due',
            field=models.DateField(blank=True, help_text='Prossima data audit prevista', null=True, verbose_name='Prossimo Audit Previsto'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='on_time_delivery_rate',
            field=models.FloatField(blank=True, help_text='Rating di Consegna Puntuale del Fornitore', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tasso di Consegna Puntuale'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, help_text='Telefono di riferimento', max_length=20, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='qualification_date',
            field=models.DateField(blank=True, help_text='Data di qualifica o revisione', null=True, verbose_name='Data di Qualifica'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='qualification_expiry',
            field=models.DateField(blank=True, help_text='Scadenza della qualifica (es. ogni 12 mesi)', null=True, verbose_name='Scadenza Qualifica'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='qualification_score',
            field=models.FloatField(blank=True, help_text='Punteggio medio di qualifica (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Punteggio di Qualifica'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='qualification_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'In attesa'), ('APPROVED', 'Approvato'), ('REJECTED', 'Respinto')], default='PENDING', help_text='Stato della qualifica del fornitore', max_length=20, null=True, verbose_name='Stato di Qualifica'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='quality_rating_avg',
            field=models.FloatField(blank=True, help_text='Rating Medio di Qualità del Fornitore', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Valutazione Media Qualità'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='reference_contact',
            field=models.CharField(blank=True, help_text='Riferimento principale', max_length=100, null=True, verbose_name='Contatto di Riferimento'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='review_notes',
            field=models.TextField(blank=True, help_text='Note di revisione e valutazione', null=True, verbose_name='Note di Revisione'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('LOW', 'Basso'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto')], default='MEDIUM', help_text='Valutazione del rischio fornitore', max_length=20, null=True, verbose_name='Livello di Rischio'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vat_number',
            field=models.CharField(blank=True, help_text='Partita IVA', max_length=20, null=True, verbose_name='Partita IVA'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(editable=False, help_text='Codice univoco del fornitore', max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Il codice fornitore deve essere alfanumerico maiuscolo', regex='^[A-Z0-9]+$')], verbose_name='Codice Fornitore'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='website',
            field=models.URLField(blank=True, help_text='Sito web aziendale', null=True, verbose_name='Sito Web'),
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Codice univoco della competenza (es. 'RSPP', 'ASPP')", max_length=50, unique=True, verbose_name='Codice Competenza')),
                ('name', models.CharField(help_text='Nome della competenza/qualifica', max_length=255, verbose_name='Nome Competenza')),
                ('description', models.TextField(blank=True, help_text='Descrizione dettagliata della competenza', null=True, verbose_name='Descrizione')),
                ('competence_category', models.CharField(choices=[('SAFETY', 'Sicurezza'), ('QUALITY', 'Qualità'), ('TECHNICAL', 'Tecnico'), ('ENERGY', 'Energia'), ('ENVIRONMENT', 'Ambiente'), ('AUDIT', 'Audit/Certificazioni'), ('OTHER', 'Altro')], default='TECHNICAL', help_text='Categoria della competenza', max_length=50, verbose_name='Categoria Competenza')),
                ('requires_certification', models.BooleanField(default=True, help_text='Indica se la competenza richiede una certificazione formale', verbose_name='Richiede Certificazione')),
                ('requires_renewal', models.BooleanField(default=False, help_text='Indica se la competenza ha una scadenza e necessita rinnovo', verbose_name='Richiede Rinnovo')),
                ('renewal_period_months', models.PositiveIntegerField(blank=True, help_text='Numero di mesi prima della scadenza (es. 12, 24, 36)', null=True, verbose_name='Periodo Rinnovo (mesi)')),
                ('is_mandatory', models.BooleanField(default=False, help_text='Competenza obbligatoria per alcune categorie di fornitori', verbose_name='È Obbligatoria')),
                ('is_active', models.BooleanField(default=True, help_text='Competenza attiva e utilizzabile', verbose_name='È Attiva')),
                ('sort_order', models.PositiveIntegerField(default=100, help_text='Ordine di visualizzazione', verbose_name='Ordine di Ordinamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('applicable_categories', models.ManyToManyField(blank=True, help_text='Categorie per cui questa competenza è rilevante', related_name='required_competences', to='vendors.category', verbose_name='Categorie Applicabili')),
            ],
            options={
                'verbose_name': 'Competenza',
                'verbose_name_plural': 'Competenze',
                'ordering': ['competence_category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Codice univoco del tipo di documento (es. 'DURC', 'VISURA')", max_length=50, unique=True, verbose_name='Codice Documento')),
                ('name', models.CharField(help_text='Nome del tipo di documento', max_length=255, verbose_name='Nome Documento')),
                ('description', models.TextField(blank=True, help_text='Descrizione dettagliata del documento', null=True, verbose_name='Descrizione')),
                ('document_category', models.CharField(choices=[('LEGAL', 'Legale/Amministrativo'), ('FINANCIAL', 'Finanziario'), ('SAFETY', 'Sicurezza'), ('QUALITY', 'Qualità'), ('TECHNICAL', 'Tecnico'), ('INSURANCE', 'Assicurativo'), ('CERTIFICATION', 'Certificazioni'), ('OTHER', 'Altro')], default='LEGAL', help_text='Categoria del documento', max_length=50, verbose_name='Categoria Documento')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Documento obbligatorio per la qualifica', verbose_name='È Obbligatorio')),
                ('requires_renewal', models.BooleanField(default=True, help_text='Documento con scadenza che necessita rinnovo', verbose_name='Richiede Rinnovo')),
                ('default_validity_days', models.PositiveIntegerField(blank=True, help_text='Numero di giorni di validità standard (es. 120 per DURC)', null=True, verbose_name='Validità Predefinita (giorni)')),
                ('is_active', models.BooleanField(default=True, help_text='Tipo di documento attivo e utilizzabile', verbose_name='È Attivo')),
                ('sort_order', models.PositiveIntegerField(default=100, help_text='Ordine di visualizzazione', verbose_name='Ordine di Ordinamento')),
                ('alert_days_before_expiry', models.PositiveIntegerField(default=30, help_text='Giorni prima della scadenza per inviare alert', verbose_name='Giorni Preavviso Scadenza')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('template_file', models.FileField(blank=True, help_text='Template o modello del documento', null=True, upload_to='document_templates/', verbose_name='File Template')),
                ('instructions', models.TextField(blank=True, help_text='Istruzioni per il fornitore su come compilare/ottenere il documento', null=True, verbose_name='Istruzioni')),
                ('applicable_categories', models.ManyToManyField(blank=True, help_text='Categorie per cui questo documento è richiesto', related_name='required_documents', to='vendors.category', verbose_name='Categorie Applicabili')),
            ],
            options={
                'verbose_name': 'Tipo Documento',
                'verbose_name_plural': 'Tipi Documento',
                'ordering': ['document_category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VendorCompetence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('has_competence', models.BooleanField(default=True, help_text='Il fornitore possiede questa competenza', verbose_name='Possiede Competenza')),
                ('certification_number', models.CharField(blank=True, help_text='Numero del certificato/attestato', max_length=100, null=True, verbose_name='Numero Certificazione')),
                ('certification_body', models.CharField(blank=True, help_text='Ente che ha rilasciato la certificazione', max_length=255, null=True, verbose_name='Ente Certificatore')),
                ('issue_date', models.DateField(blank=True, help_text='Data di rilascio della certificazione', null=True, verbose_name='Data Rilascio')),
                ('expiry_date', models.DateField(blank=True, help_text='Data di scadenza della certificazione', null=True, verbose_name='Data Scadenza')),
                ('verified', models.BooleanField(default=False, help_text="Competenza verificata dall'azienda", verbose_name='Verificata')),
                ('verified_by', models.CharField(blank=True, help_text='Persona che ha verificato la competenza', max_length=255, null=True, verbose_name='Verificata da')),
                ('verified_date', models.DateField(blank=True, help_text='Data di verifica', null=True, verbose_name='Data Verifica')),
                ('document_file', models.FileField(blank=True, help_text='File del certificato/attestato', null=True, upload_to='vendor_competences/%Y/%m/', verbose_name='File Documento')),
                ('notes', models.TextField(blank=True, help_text='Note aggiuntive sulla competenza', null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_assignments', to='vendors.competence', verbose_name='Competenza')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_competences', to='vendors.vendor', verbose_name='Fornitore')),
            ],
            options={
                'verbose_name': 'Competenza Fornitore',
                'verbose_name_plural': 'Competenze Fornitori',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='vendor',
            name='competences',
            field=models.ManyToManyField(blank=True, help_text='Competenze possedute dal fornitore', related_name='vendors_with_competence', through='vendors.VendorCompetence', to='vendors.competence', verbose_name='Competenze'),
        ),
        migrations.CreateModel(
            name='VendorDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_number', models.CharField(blank=True, help_text='Numero o riferimento del documento', max_length=100, null=True, verbose_name='Numero Documento')),
                ('issue_date', models.DateField(blank=True, help_text='Data di emissione del documento', null=True, verbose_name='Data Emissione')),
                ('expiry_date', models.DateField(blank=True, help_text='Data di scadenza del documento', null=True, verbose_name='Data Scadenza')),
                ('status', models.CharField(choices=[('PENDING', 'In attesa'), ('SUBMITTED', 'Inviato'), ('UNDER_REVIEW', 'In revisione'), ('APPROVED', 'Approvato'), ('REJECTED', 'Respinto'), ('EXPIRED', 'Scaduto')], default='PENDING', help_text='Stato del documento', max_length=20, verbose_name='Stato')),
                ('verified', models.BooleanField(default=False, help_text="Documento verificato dall'azienda", verbose_name='Verificato')),
                ('verified_by', models.CharField(blank=True, help_text='Persona che ha verificato il documento', max_length=255, null=True, verbose_name='Verificato da')),
                ('verified_date', models.DateField(blank=True, help_text='Data di verifica', null=True, verbose_name='Data Verifica')),
                ('document_file', models.FileField(blank=True, help_text='File del documento caricato', null=True, upload_to='vendor_documents/%Y/%m/', verbose_name='File Documento')),
                ('notes', models.TextField(blank=True, help_text='Note aggiuntive sul documento', null=True, verbose_name='Note')),
                ('rejection_reason', models.TextField(blank=True, help_text='Motivo del rifiuto (se applicabile)', null=True, verbose_name='Motivo Rifiuto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('uploaded_by', models.CharField(blank=True, help_text='Utente che ha caricato il documento', max_length=255, null=True, verbose_name='Caricato da')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_submissions', to='vendors.documenttype', verbose_name='Tipo Documento')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_documents', to='vendors.vendor', verbose_name='Fornitore')),
            ],
            options={
                'verbose_name': 'Documento Fornitore',
                'verbose_name_plural': 'Documenti Fornitori',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='competence',
            index=models.Index(fields=['code'], name='vendors_com_code_3261f8_idx'),
        ),
        migrations.AddIndex(
            model_name='competence',
            index=models.Index(fields=['competence_category', 'is_active'], name='vendors_com_compete_221997_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttype',
            index=models.Index(fields=['code'], name='vendors_doc_code_1c3754_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttype',
            index=models.Index(fields=['document_category', 'is_active'], name='vendors_doc_documen_f9b28a_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttype',
            index=models.Index(fields=['is_mandatory'], name='vendors_doc_is_mand_135235_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorcompetence',
            index=models.Index(fields=['vendor', 'competence'], name='vendors_ven_vendor__cf03de_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorcompetence',
            index=models.Index(fields=['expiry_date'], name='vendors_ven_expiry__d10954_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorcompetence',
            index=models.Index(fields=['verified'], name='vendors_ven_verifie_25ea22_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vendorcompetence',
            unique_together={('vendor', 'competence')},
        ),
        migrations.AddIndex(
            model_name='vendordocument',
            index=models.Index(fields=['vendor', 'document_type'], name='vendors_ven_vendor__6ff623_idx'),
        ),
        migrations.AddIndex(
            model_name='vendordocument',
            index=models.Index(fields=['status'], name='vendors_ven_status_72973d_idx'),
        ),
        migrations.AddIndex(
            model_name='vendordocument',
            index=models.Index(fields=['expiry_date'], name='vendors_ven_expiry__1f1d82_idx'),
        ),
        migrations.AddIndex(
            model_name='vendordocument',
            index=models.Index(fields=['verified'], name='vendors_ven_verifie_a101d7_idx'),
        ),
    ]
