# Generated by Django 5.0.6 on 2025-11-05 18:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_alter_address_options_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCriterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('COMM', 'Valutazione Commerciale'), ('CONS', 'Valutazione del Servizio (Consulting)'), ('FCB', 'Valutazione del Servizio (FCB)'), ('MED', 'Valutazione del Servizio (MED)'), ('PROD_NONTEC', 'Valutazione Prodotto non tecnologico'), ('PROD_TEC', 'Valutazione Prodotto tecnologico')], max_length=20, verbose_name='Categoria di Valutazione')),
                ('code', models.CharField(help_text='Codice univoco del criterio (es. COMM_01, FCB_03, PROD_TEC_02)', max_length=50, unique=True, verbose_name='Codice Criterio')),
                ('name', models.CharField(help_text="Nome del criterio di valutazione (es. 'Efficienza del servizio')", max_length=255, verbose_name='Nome del Criterio')),
                ('description', models.TextField(blank=True, help_text='Descrizione dettagliata del criterio', null=True, verbose_name='Descrizione')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Criterio di Valutazione',
                'verbose_name_plural': 'Criteri di Valutazione',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='QualificationType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Codice univoco del titolo di studio o qualifica (es. 'DIP', 'LAU', 'MAS')", max_length=50, unique=True, verbose_name='Codice Titolo')),
                ('name', models.CharField(help_text="Nome completo del titolo di studio (es. 'Diploma tecnico', 'Laurea triennale')", max_length=255, verbose_name='Nome Titolo')),
                ('description', models.TextField(blank=True, help_text='Descrizione aggiuntiva del titolo di studio', null=True, verbose_name='Descrizione')),
                ('level', models.CharField(blank=True, help_text='Livello di qualifica secondo il Quadro Europeo delle Qualifiche (EQF)', max_length=20, null=True, verbose_name='Livello EQF')),
                ('is_active', models.BooleanField(default=True, help_text='Titolo di studio attivo e selezionabile', verbose_name='È Attivo')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Ordine di Ordinamento')),
            ],
            options={
                'verbose_name': 'Tipo di Qualifica / Titolo di Studio',
                'verbose_name_plural': 'Tipi di Qualifica / Titoli di Studio',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='address',
            name='notes',
        ),
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.CharField(blank=True, help_text='Regione', max_length=100, null=True, verbose_name='Regione'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='ambulatory_service',
            field=models.TextField(blank=True, help_text='Descrizione dei servizi ambulatoriali offerti dal fornitore', null=True, verbose_name='Servizio Ambulatoriale'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='begin_experience_date',
            field=models.DateField(blank=True, help_text="Data di inizio dell'esperienza", null=True, verbose_name='Data Inizio Esperienza'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='cluster_cost',
            field=models.CharField(choices=[('01', 'GenSpDirPre'), ('02', 'GenSpDirPre; Antincendio; Attrezzature'), ('03', 'GenSpDirPre; Segnaletica Stradale'), ('04', 'Antincendio'), ('05', 'Primo Soccorso'), ('06', 'Primo Soccorso BLSD'), ('08', 'Attrezzature'), ('09', 'Elearning'), ('11', 'Manageriale'), ('12', 'Attestati'), ('19', 'Tutti'), ('20', 'Ambientale')], default='01', help_text='Raggruppamento di costo per tipologia di servizio', max_length=50, verbose_name='Cluster Costo'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contractual_end_date',
            field=models.DateField(blank=True, help_text='Data di fine del contratto con il fornitore', null=True, verbose_name='Data Fine Contratto'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contractual_start_date',
            field=models.DateField(blank=True, help_text='Data di inizio del contratto con il fornitore', null=True, verbose_name='Data Inizio Contratto'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contractual_status',
            field=models.CharField(choices=[('00', 'Da verificare'), ('02', 'Fare RAI'), ('03', 'RAI Effettuata'), ('04', 'Contrattualizzato'), ('05', 'Da contrattualizzare ad esigenza'), ('06', 'Contratto Scaduto'), ('99', 'Non Usare')], default='00', help_text='Indica lo stato contrattuale del fornitore', max_length=2, verbose_name='Stato Contrattuale'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contractual_terms',
            field=models.TextField(blank=True, help_text='Termini e condizioni del contratto con il fornitore', null=True, verbose_name='Termini Contrattuali'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='doctor_cv',
            field=models.BooleanField(default=False, help_text='Indica se il curriculum vitae del medico è disponibile', verbose_name='CV del Medico Disponibile'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='doctor_cv2',
            field=models.BooleanField(default=False, help_text='Indica se il secondo curriculum vitae del medico è disponibile', verbose_name='CV2 del Medico Disponibile'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='doctor_registration',
            field=models.TextField(blank=True, help_text="Descrizione del titolo di iscrizione all'albo dei medici", null=True, verbose_name='Titolo Iscrizione Albo Medici'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='laboratory_service',
            field=models.BooleanField(default=False, help_text='Indica se il fornitore offre servizi di laboratorio', verbose_name='Servizio di Laboratorio'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='licensed_physician_year',
            field=models.IntegerField(blank=True, help_text='Anno di licenza del medico associato al fornitore', null=True, verbose_name='Anno di Licenza del Medico'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='mobile_device',
            field=models.BooleanField(default=False, help_text='Indica se il fornitore utilizza dispositivi mobili per le operazioni', verbose_name='Dispositivo Mobile'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='other_medical_service',
            field=models.TextField(blank=True, help_text='Descrizione di altri servizi medici offerti dal fornitore', null=True, verbose_name='Altri Servizi Medici'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='reference_person',
            field=models.CharField(blank=True, help_text='Persona di riferimento', max_length=100, null=True, verbose_name='Persona di Riferimento'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='user_account',
            field=models.ForeignKey(blank=True, help_text='Utente di aggiornamento associato al fornitore', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to=settings.AUTH_USER_MODEL, verbose_name='Utente di aggiornamento'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_final_evaluation',
            field=models.CharField(blank=True, choices=[('DA VALUTARE', 'Da Valutare'), ('NEGATIVO', 'Negativo'), ('POSITIVO', 'Positivo'), ('MOLTO POSITIVO', 'Molto Positivo')], default='DA VALUTARE', help_text='Valutazione finale complessiva del fornitore', max_length=20, null=True, verbose_name='Valutazione Finale del Fornitore'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_task_description',
            field=models.TextField(blank=True, help_text='Descrizione delle attività svolte dal fornitore', null=True, verbose_name='Descrizione Attività Fornitore'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_typye',
            field=models.CharField(blank=True, choices=[('Società', 'Società'), ('Professionista', 'Professionista'), ('Dipendente', 'Dipendente'), ('Dipendente + Libero professionista', 'Dipendente + Libero professionista'), ('Disoccupato', 'Disoccupato'), ('Libero Professionista', 'Libero Professionista'), ('Presso Studio', 'Presso Studio'), ('Prestazione Occasionale', 'Prestazione Occasionale'), ('Società/professionista', 'Società/professionista'), ('Internazionale', 'Internazionale')], default='Società', help_text='Tipo di fornitore', max_length=50, null=True, verbose_name='Tipo di Fornitore'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='qualification_type',
            field=models.ForeignKey(blank=True, help_text='Titolo di studio o qualifica del fornitore', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='vendors.qualificationtype', verbose_name='Titolo di Studio / Tipo di Qualifica'),
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Codice univoco del servizio o tipologia (es. 'CONSULENZA', 'CONS_SIC')", max_length=50, unique=True, verbose_name='Codice Servizio')),
                ('name', models.CharField(help_text='Nome della tipologia o del servizio specifico', max_length=255, verbose_name='Nome Servizio')),
                ('description', models.TextField(blank=True, help_text='Descrizione dettagliata del servizio', null=True, verbose_name='Descrizione')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se il servizio è attivo', verbose_name='È Attivo')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Ordine di Ordinamento')),
                ('parent', models.ForeignKey(blank=True, help_text='Tipologia padre (lascia vuoto se è una categoria principale)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subservices', to='vendors.servicetype', verbose_name='Tipologia Padre')),
            ],
            options={
                'verbose_name': 'Tipo/Servizio',
                'verbose_name_plural': 'Tipologie e Servizi',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='vendor',
            name='service_type',
            field=models.ForeignKey(blank=True, help_text='Servizio specifico o tipologia principale del fornitore', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='vendors.servicetype', verbose_name='Servizio / Tipologia Servizio'),
        ),
        migrations.CreateModel(
            name='VendorEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(choices=[(1, 'Scarso'), (2, 'Insufficiente'), (3, 'Non sufficiente'), (4, 'Al limite della sufficienza'), (5, 'Sufficiente'), (6, 'Buono'), (7, 'Ottimo'), (8, 'Eccellente')], help_text='Valutazione da 1 (Scarso) a 8 (Eccellente)', verbose_name='Punteggio')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('evaluated_at', models.DateField(auto_now_add=True, verbose_name='Data Valutazione')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_scores', to='vendors.evaluationcriterion', verbose_name='Criterio di Valutazione')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='vendors.vendor', verbose_name='Fornitore')),
            ],
            options={
                'verbose_name': 'Valutazione Fornitore',
                'verbose_name_plural': 'Valutazioni Fornitori',
                'unique_together': {('vendor', 'criterion')},
            },
        ),
    ]
