# Generated by Django 5.0.6 on 2025-11-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_evaluationcriterion_qualificationtype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualificationtype',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Titolo', 'verbose_name_plural': 'Titoli'},
        ),
        migrations.AlterModelOptions(
            name='vendorcompetence',
            options={'ordering': ['-created_at'], 'verbose_name': 'Competenza', 'verbose_name_plural': 'Competenze'},
        ),
        migrations.AlterModelOptions(
            name='vendordocument',
            options={'ordering': ['-created_at'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documenti'},
        ),
        migrations.AlterModelOptions(
            name='vendorevaluation',
            options={'verbose_name': 'Valutazione', 'verbose_name_plural': 'Valutazioni'},
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='vendor_typye',
            new_name='vendor_type',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='country',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='iso_certifications',
        ),
        migrations.AddField(
            model_name='vendor',
            name='albo_zucchetti',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Inserito in Albo Zucchetti'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='competences_zone',
            field=models.CharField(blank=True, help_text='Zona geografica delle competenze del fornitore', max_length=255, null=True, verbose_name='Zona Competenze'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_ico_consultant',
            field=models.BooleanField(default=False, help_text='Indica se il fornitore è un consulente ICO', verbose_name='È Consulente ICO'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='laboratory_independent',
            field=models.BooleanField(default=False, help_text='Indica se il laboratorio è indipendente', null=True, verbose_name='Laboratorio Indipendente'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='old_code',
            field=models.CharField(blank=True, help_text='Vecchio codice univoco del fornitore, se applicabile', max_length=10, null=True, unique=True, verbose_name='Vecchio Codice Fornitore'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='service_additional',
            field=models.CharField(blank=True, help_text='Descrizione di servizi aggiuntivi offerti dal fornitore', max_length=255, null=True, verbose_name='Servizio Aggiuntivo'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='service_note',
            field=models.TextField(blank=True, help_text='Note aggiuntive sul servizio offerto dal fornitore', null=True, verbose_name='Note sul Servizio'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_management_update',
            field=models.CharField(blank=True, help_text='Gestione aggiornamenti del fornitore', max_length=100, null=True, verbose_name='Gestione aggiornamenti'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_medical_service',
            field=models.CharField(blank=True, choices=[('ALTRI_PROF', 'Altri Professionisti'), ('ALTRO', 'ALTRO'), ('AMBULANZE', 'Ambulanze'), ('CENTRO_MEDICO', 'Centro medico/Poliambulatorio'), ('DOCENTE', 'Docente'), ('FORN_SANITARIE', 'Forniture sanitarie/Elettromedicali'), ('INFERMIERE', 'Infermiere'), ('LABORATORIO', 'Laboratorio'), ('MEDICINA_LAVORO', 'Medicina del Lavoro'), ('MEDICO_COMPETENTE', 'Medico Competente'), ('MEDICO_GENERICO', 'Medico Generico'), ('MEDICO_SPECIALISTA', 'Medico Specialista'), ('RIFIUTI', 'Rifiuti'), ('SOCIETA_SANITARIA', 'Società Infermieri-Medici-Assistenti sociali')], default='ALTRO', help_text='Tipologia di servizio medico o sanitario fornito', max_length=50, null=True, verbose_name='Servizio Sanitario/Professionale'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='year_of_establishment',
            field=models.IntegerField(blank=True, help_text='Anno di Specializzazione o Fondazione', null=True, verbose_name='Anno di Specializzazione/Fondazione'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='licensed_physician_year',
            field=models.IntegerField(blank=True, help_text="Medico autorizzato dall'anno", null=True, verbose_name="Medico autorizzato dall'anno"),
        ),
    ]
