# Generated by Django 5.0.6 on 2025-11-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_alter_qualificationtype_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='year_of_establishment',
        ),
        migrations.AddField(
            model_name='vendor',
            name='date_of_establishment',
            field=models.DateField(blank=True, help_text='Data di Specializzazione o Fondazione', null=True, verbose_name='Data di Specializzazione/Fondazione'),
        ),
    ]
