# Generated by Django 5.0.6 on 2025-11-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_alter_vendor_albo_zucchetti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, help_text='Telefono di riferimento', max_length=100, null=True, verbose_name='Telefono'),
        ),
    ]
