# Generated by Django 5.0.6 on 2025-11-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_alter_address_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='cluster_cost',
        ),
        migrations.AddField(
            model_name='vendor',
            name='cluster_corso',
            field=models.CharField(blank=True, choices=[('01', 'GenSpDirPre'), ('02', 'GenSpDirPre; Antincendio; Attrezzature'), ('03', 'GenSpDirPre; Segnaletica Stradale'), ('04', 'Antincendio'), ('05', 'Primo Soccorso'), ('06', 'Primo Soccorso BLSD'), ('08', 'Attrezzature'), ('09', 'Elearning'), ('11', 'Manageriale'), ('12', 'Attestati'), ('19', 'Tutti'), ('20', 'Ambientale')], help_text='Raggruppamento di corso per tipologia di servizio', max_length=50, null=True, verbose_name='Cluster Corso'),
        ),
    ]
