# Generated by Django 5.0.6 on 2025-11-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0015_qualificationtype_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendordocument',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='vendordocument',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='DocumentType',
        ),
        migrations.DeleteModel(
            name='VendorDocument',
        ),
    ]
