# Generated by Django 5.0.6 on 2026-02-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0017_vendor_vendor_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prezzo del servizio', max_digits=10, null=True, verbose_name='Prezzo orario del servizio'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('LOW', 'Basso'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto')], default='MEDIUM', help_text="Valutazione dell'affidabilità/rischio del fornitore", max_length=20, null=True, verbose_name='Livello di Affidabilità/Rischio'),
        ),
    ]
