# Generated by Django 5.0.6 on 2026-02-15 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0018_alter_competence_options_competence_requirement_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorcompetence',
            options={'ordering': ['-created_at'], 'verbose_name': 'Requisito Professionale Assegnato', 'verbose_name_plural': 'Requisiti Professionali Assegnati'},
        ),
        migrations.AlterField(
            model_name='competence',
            name='code',
            field=models.CharField(help_text="Codice univoco del requisito professionale (es. 'RSPP', 'ASPP')", max_length=50, unique=True, verbose_name='Codice Requisito'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='competence_category',
            field=models.CharField(choices=[('SAFETY', 'Sicurezza'), ('QUALITY', 'Qualità'), ('TECHNICAL', 'Tecnico'), ('ENERGY', 'Energia'), ('ENVIRONMENT', 'Ambiente'), ('AUDIT', 'Audit/Certificazioni'), ('OTHER', 'Altro')], default='TECHNICAL', help_text='Categoria del requisito professionale', max_length=50, verbose_name='Categoria Requisito Professionale'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='description',
            field=models.TextField(blank=True, help_text='Descrizione dettagliata del requisito professionale', null=True, verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Requisito professionale attivo e utilizzabile', verbose_name='È Attivo'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='is_mandatory',
            field=models.BooleanField(default=False, help_text='Requisito professionale obbligatorio per alcune categorie di fornitori', verbose_name='È Obbligatorio'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='name',
            field=models.CharField(help_text='Nome del requisito professionale', max_length=255, verbose_name='Nome Requisito Professionale'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='requirement_type',
            field=models.CharField(blank=True, choices=[('competenza', 'Competenza'), ('qualifica', 'Qualifica')], max_length=20, null=True, verbose_name='Requisito Professionale'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='requires_certification',
            field=models.BooleanField(default=True, help_text='Indica se il requisito professionale richiede una certificazione formale', verbose_name='Richiede Certificazione'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='requires_renewal',
            field=models.BooleanField(default=False, help_text='Indica se il requisito professionale ha una scadenza e necessita rinnovo', verbose_name='Richiede Rinnovo'),
        ),
        migrations.AlterField(
            model_name='vendorcompetence',
            name='competence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_assignments', to='vendors.competence', verbose_name='Requisito Professionale'),
        ),
        migrations.AlterField(
            model_name='vendorcompetence',
            name='has_competence',
            field=models.BooleanField(default=True, help_text='Il fornitore possiede questo requisito professionale', verbose_name='Possiede Requisito Professionale'),
        ),
    ]
