# Generated by Django 5.0.6 on 2026-02-18 18:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


def remove_fields_if_exist(apps, schema_editor):
    """
    Rimuovi i campi solo se esistono nel database
    """
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Ottieni le colonne esistenti nella tabella vendors_vendor
        cursor.execute("""
            SELECT COLUMN_NAME 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'vendors_vendor'
        """)
        existing_columns = [row[0] for row in cursor.fetchall()]
        
        # Rimuovi solo le colonne che esistono
        fields_to_remove = ['begin_experience_date', 'service_additional', 'service_note', 'service_type']
        for field in fields_to_remove:
            if field in existing_columns:
                cursor.execute(f"ALTER TABLE vendors_vendor DROP COLUMN {field}")


def reverse_remove_fields(apps, schema_editor):
    """
    Non facciamo nulla nel reverse - i campi non devono essere ricreati
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0018_alter_competence_options_competence_requirement_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorcompetence',
            options={'ordering': ['-created_at'], 'verbose_name': 'Requisito Professionale Assegnato', 'verbose_name_plural': 'Requisiti Professionali Assegnati'},
        ),
        migrations.RunPython(remove_fields_if_exist, reverse_remove_fields),
        migrations.AddField(
            model_name='servicetype',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prezzo del servizio', max_digits=10, null=True, verbose_name='Prezzo orario del servizio'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='code',
            field=models.CharField(help_text="Codice univoco del requisito professionale (es. 'RSPP', 'ASPP')", max_length=50, unique=True, verbose_name='Codice Requisito'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='competence_category',
            field=models.CharField(choices=[('SAFETY', 'Sicurezza'), ('QUALITY', 'Qualità'), ('TECHNICAL', 'Tecnico'), ('ENERGY', 'Energia'), ('ENVIRONMENT', 'Ambiente'), ('AUDIT', 'Audit/Certificazioni'), ('OTHER', 'Altro')], default='TECHNICAL', help_text='Categoria del requisito professionale', max_length=50, verbose_name='Categoria Requisito Professionale'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='description',
            field=models.TextField(blank=True, help_text='Descrizione dettagliata del requisito professionale', null=True, verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Requisito professionale attivo e utilizzabile', verbose_name='È Attivo'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='is_mandatory',
            field=models.BooleanField(default=False, help_text='Requisito professionale obbligatorio per alcune categorie di fornitori', verbose_name='È Obbligatorio'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='name',
            field=models.CharField(help_text='Nome del requisito professionale', max_length=255, verbose_name='Nome Requisito Professionale'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='requirement_type',
            field=models.CharField(blank=True, choices=[('competenza', 'Competenza'), ('qualifica', 'Qualifica'), ('iscrizione_albo', 'Iscrizione Albo')], default='qualifica', max_length=20, null=True, verbose_name='Requisito Professionale'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='requires_certification',
            field=models.BooleanField(default=True, help_text='Indica se il requisito professionale richiede una certificazione formale', verbose_name='Richiede Certificazione'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='requires_renewal',
            field=models.BooleanField(default=False, help_text='Indica se il requisito professionale ha una scadenza e necessita rinnovo', verbose_name='Richiede Rinnovo'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('LOW', 'Basso'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto')], default='MEDIUM', help_text="Valutazione dell'affidabilità/rischio del fornitore", max_length=20, null=True, verbose_name='Livello di Affidabilità/Rischio'),
        ),
        migrations.AlterField(
            model_name='vendorcompetence',
            name='competence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_assignments', to='vendors.competence', verbose_name='Requisito Professionale'),
        ),
        migrations.AlterField(
            model_name='vendorcompetence',
            name='has_competence',
            field=models.BooleanField(default=True, help_text='Il fornitore possiede questo requisito professionale', verbose_name='Possiede Requisito Professionale'),
        ),
        migrations.CreateModel(
            name='VendorService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False, help_text='Indica se questo è il servizio principale del fornitore', verbose_name='Servizio Principale')),
                ('start_date', models.DateField(blank=True, help_text='Data di inizio erogazione del servizio', null=True, verbose_name='Data Inizio Erogazione')),
                ('end_date', models.DateField(blank=True, help_text='Data di fine erogazione del servizio (se applicabile)', null=True, verbose_name='Data Fine Erogazione')),
                ('notes', models.TextField(blank=True, help_text='Note aggiuntive sul servizio erogato', null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_assignments', to='vendors.servicetype', verbose_name='Servizio')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_services', to='vendors.vendor', verbose_name='Fornitore')),
            ],
            options={
                'verbose_name': 'Servizio Fornitore',
                'verbose_name_plural': 'Servizi Fornitori',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='vendor',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Servizi erogati dal fornitore', related_name='vendors_providing_service', through='vendors.VendorService', to='vendors.servicetype', verbose_name='Servizi Erogati'),
        ),
        migrations.AddIndex(
            model_name='vendorservice',
            index=models.Index(fields=['vendor', 'service_type'], name='vendors_ven_vendor__8efec1_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorservice',
            index=models.Index(fields=['is_primary'], name='vendors_ven_is_prim_6498b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vendorservice',
            unique_together={('vendor', 'service_type')},
        ),
    ]
