# Generated by Django 5.0.6 on 2026-02-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0019_alter_vendorcompetence_options_alter_competence_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='requirement_type',
            field=models.CharField(blank=True, choices=[('competenza', 'Competenza'), ('qualifica', 'Qualifica'), ('iscrizione_albo', 'Iscrizione Albo')], default='qualifica', max_length=20, null=True, verbose_name='Requisito Professionale'),
        ),
    ]
