# Generated by Django 5.0.6 on 2026-02-16 15:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0020_alter_competence_requirement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='service_type',
            field=models.ForeignKey(blank=True, help_text="DEPRECATO: Usa il campo 'services' per gestire più servizi", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors_deprecated', to='vendors.servicetype', verbose_name='Servizio / Tipologia Servizio (Deprecato)'),
        ),
        migrations.CreateModel(
            name='VendorService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False, help_text='Indica se questo è il servizio principale del fornitore', verbose_name='Servizio Principale')),
                ('start_date', models.DateField(blank=True, help_text='Data di inizio erogazione del servizio', null=True, verbose_name='Data Inizio Erogazione')),
                ('end_date', models.DateField(blank=True, help_text='Data di fine erogazione del servizio (se applicabile)', null=True, verbose_name='Data Fine Erogazione')),
                ('notes', models.TextField(blank=True, help_text='Note aggiuntive sul servizio erogato', null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_assignments', to='vendors.servicetype', verbose_name='Servizio')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_services', to='vendors.vendor', verbose_name='Fornitore')),
            ],
            options={
                'verbose_name': 'Servizio Fornitore',
                'verbose_name_plural': 'Servizi Fornitori',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='vendor',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Servizi erogati dal fornitore', related_name='vendors_providing_service', through='vendors.VendorService', to='vendors.servicetype', verbose_name='Servizi Erogati'),
        ),
        migrations.AddIndex(
            model_name='vendorservice',
            index=models.Index(fields=['vendor', 'service_type'], name='vendors_ven_vendor__8efec1_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorservice',
            index=models.Index(fields=['is_primary'], name='vendors_ven_is_prim_6498b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vendorservice',
            unique_together={('vendor', 'service_type')},
        ),
    ]
