# Generated by Django 5.0.6 on 2026-04-17 14:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0021_remove_servicetype_price_vendorservice_hourly_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(help_text='Codice identificativo del contratto', max_length=50, unique=True, verbose_name='Numero Contratto')),
                ('title', models.CharField(help_text='Descrizione breve del contratto', max_length=255, verbose_name='Titolo')),
                ('status', models.CharField(choices=[('DRAFT', 'Bozza'), ('ACTIVE', 'Attivo'), ('EXPIRED', 'Scaduto'), ('TERMINATED', 'Risolto'), ('SUSPENDED', 'Sospeso')], default='DRAFT', max_length=20, verbose_name='Stato')),
                ('start_date', models.DateField(help_text='Data di decorrenza del contratto', verbose_name='Data Inizio')),
                ('end_date', models.DateField(blank=True, help_text='Data di scadenza del contratto', null=True, verbose_name='Data Fine')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Importo totale del contratto', max_digits=12, null=True, verbose_name='Importo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('services', models.ManyToManyField(blank=True, help_text='Servizi del fornitore collegati a questo contratto', related_name='contracts', to='vendors.vendorservice', verbose_name='Servizi Associati')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='vendors.vendor', verbose_name='Fornitore')),
            ],
            options={
                'verbose_name': 'Contratto',
                'verbose_name_plural': 'Contratti',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['vendor', 'status'], name='vendors_con_vendor__ea58c2_idx'), models.Index(fields=['contract_number'], name='vendors_con_contrac_92288b_idx')],
            },
        ),
    ]
