# Generated by Django 5.0.6 on 2026-02-16 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0021_alter_vendor_service_type_vendorservice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='begin_experience_date',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='service_additional',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='service_note',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='service_type',
        ),
    ]
