# Generated by Django 5.0.6 on 2026-04-17 15:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0023_move_contract_to_vendorservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenceZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Nome descrittivo della zona (es. 'Tutta l'Italia', 'Nord Italia')", max_length=255, unique=True, verbose_name='Nome Zona')),
                ('description', models.TextField(blank=True, help_text='Descrizione dettagliata della zona di competenza', null=True, verbose_name='Descrizione')),
                ('is_active', models.BooleanField(default=True, verbose_name='È Attiva')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
            ],
            options={
                'verbose_name': 'Zona di Competenza',
                'verbose_name_plural': 'Zone di Competenza',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Codice ISO 3166-1 alpha-2 (es. 'IT', 'DE', 'FR')", max_length=3, unique=True, verbose_name='Codice ISO')),
                ('name', models.CharField(help_text='Nome della nazione', max_length=100, verbose_name='Nome Nazione')),
                ('is_active', models.BooleanField(default=True, verbose_name='È Attiva')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Ordine')),
            ],
            options={
                'verbose_name': 'Nazione',
                'verbose_name_plural': 'Nazioni',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='vendor',
            name='competences_zone',
            field=models.CharField(blank=True, help_text='Zona geografica delle competenze del fornitore (campo legacy)', max_length=255, null=True, verbose_name='Zona Competenze'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='competence_zones',
            field=models.ManyToManyField(blank=True, help_text='Zone di competenza geografica del fornitore', related_name='vendors', to='vendors.competencezone', verbose_name='Zone di Competenza'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Codice univoco della regione (es. 'LOM', 'VEN')", max_length=10, unique=True, verbose_name='Codice Regione')),
                ('name', models.CharField(help_text='Nome della regione', max_length=100, verbose_name='Nome Regione')),
                ('is_active', models.BooleanField(default=True, verbose_name='È Attiva')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Ordine')),
                ('country', models.ForeignKey(help_text='Nazione di appartenenza', on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='vendors.country', verbose_name='Nazione')),
            ],
            options={
                'verbose_name': 'Regione',
                'verbose_name_plural': 'Regioni',
                'ordering': ['country__name', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Sigla della provincia (es. 'MI', 'RM', 'RA')", max_length=10, unique=True, verbose_name='Sigla Provincia')),
                ('name', models.CharField(help_text='Nome della provincia', max_length=100, verbose_name='Nome Provincia')),
                ('is_active', models.BooleanField(default=True, verbose_name='È Attiva')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Ordine')),
                ('region', models.ForeignKey(help_text='Regione di appartenenza', on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='vendors.region', verbose_name='Regione')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Province',
                'ordering': ['region__name', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompetenceZoneRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('INCLUDE', 'Includi'), ('EXCLUDE', 'Escludi')], default='INCLUDE', help_text='Includi o escludi questa area geografica', max_length=10, verbose_name='Tipo Regola')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='vendors.competencezone', verbose_name='Zona di Competenza')),
                ('country', models.ForeignKey(blank=True, help_text='Seleziona per regola a livello nazionale', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_rules', to='vendors.country', verbose_name='Nazione')),
                ('province', models.ForeignKey(blank=True, help_text='Seleziona per regola a livello provinciale', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_rules', to='vendors.province', verbose_name='Provincia')),
                ('region', models.ForeignKey(blank=True, help_text='Seleziona per regola a livello regionale', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_rules', to='vendors.region', verbose_name='Regione')),
            ],
            options={
                'verbose_name': 'Regola Zona di Competenza',
                'verbose_name_plural': 'Regole Zone di Competenza',
                'ordering': ['rule_type', 'id'],
            },
        ),
    ]
