# Generated by Django 5.0.6 on 2026-04-17 17:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0027_remove_competence_requirement_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Cognome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('role', models.CharField(blank=True, help_text='Ruolo o qualifica del valutatore', max_length=150, null=True, verbose_name='Ruolo')),
                ('department', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dipartimento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data Aggiornamento')),
            ],
            options={
                'verbose_name': 'Valutatore',
                'verbose_name_plural': 'Valutatori',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='vendorevaluation',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='vendors.evaluator', verbose_name='Valutatore'),
        ),
    ]
