# Generated by Django 5.0.6 on 2026-04-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0030_remove_vendor_evaluation_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='embyon_blocked',
            field=models.BooleanField(default=False, help_text='Indica se il fornitore risulta bloccato in Embyon', verbose_name='Bloccato in Embyon'),
        ),
    ]
