# Generated by Django 5.0.6 on 2026-05-19 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0031_vendor_embyon_blocked_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('ACCORDO_QUADRO', 'Accordo quadro'), ('ORDINE', 'Ordine'), ('ORDINE_RICORRENTE', 'Ordine ricorrente'), ('FORNITURA_OCCASIONALE', 'Fornitura occasionale')], help_text='Tipologia del contratto', max_length=30, null=True, verbose_name='Tipo contratto'),
        ),
        migrations.AddField(
            model_name='contract',
            name='reference_person',
            field=models.CharField(blank=True, help_text='Persona di riferimento per il contratto', max_length=100, null=True, verbose_name='Persona di riferimento'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='managed_by',
            field=models.ForeignKey(blank=True, help_text='Utente Back Office o Admin responsabile della gestione del fornitore', limit_choices_to={'role__in': ['admin', 'bo_user']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_vendors', to=settings.AUTH_USER_MODEL, verbose_name='Utente gestione fornitore'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Note/Ulteriori condizioni contrattuali'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='old_code',
            field=models.CharField(blank=True, help_text='Codice Embyon (ex Vecchio codice fornitore)', max_length=10, null=True, unique=True, verbose_name='Codice Embyon'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='qualification_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'In attesa'), ('APPROVED', 'Approvato'), ('REJECTED', 'Respinto'), ('TO_REVIEW', 'Da Revisionare')], default='PENDING', help_text='Stato della qualifica del fornitore', max_length=20, null=True, verbose_name='Stato di Qualifica'),
        ),
        migrations.AlterField(
            model_name='vendorevaluation',
            name='evaluation_frequency',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='vendors.evaluationfrequency', verbose_name='Frequenza di Valutazione'),
        ),
    ]
