# Generated by Django 4.2.7 on 2026-05-19 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0032_alter_vendorevaluation_evaluation_frequency'),
        ('vendors', '0032_vendor_admin_changes'),
    ]

    operations = [
    ]
