# Generated by Django 5.0.6 on 2026-09-09 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0034_rename_embyon_blocked_embyon_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenceSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nome del set di requisiti (es. 'MDL - Medico Competente')", max_length=255, verbose_name='Nome Set')),
                ('description', models.TextField(blank=True, help_text='Descrizione del set di requisiti professionali', null=True, verbose_name='Descrizione')),
                ('is_active', models.BooleanField(default=True, help_text='Set attivo e selezionabile', verbose_name='Attivo')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Ordine di visualizzazione', verbose_name='Ordine')),
                ('category', models.ForeignKey(blank=True, help_text='Classificazione del fornitore a cui si applica il set (vuoto = applicabile a tutte le classificazioni)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competence_sets', to='vendors.category', verbose_name='Classificazione')),
                ('competences', models.ManyToManyField(help_text='Requisiti professionali inclusi nel set', related_name='competence_sets', to='vendors.competence', verbose_name='Requisiti Professionali')),
            ],
            options={
                'verbose_name': 'Set Requisiti Professionali',
                'verbose_name_plural': 'Set Requisiti Professionali',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nome del set di servizi (es. 'MEDICINA DEL LAVORO')", max_length=255, verbose_name='Nome Set')),
                ('description', models.TextField(blank=True, help_text='Descrizione del set di servizi', null=True, verbose_name='Descrizione')),
                ('is_active', models.BooleanField(default=True, help_text='Set attivo e selezionabile', verbose_name='Attivo')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Ordine di visualizzazione', verbose_name='Ordine')),
                ('category', models.ForeignKey(blank=True, help_text='Classificazione del fornitore a cui si applica il set (vuoto = applicabile a tutte le classificazioni)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_sets', to='vendors.category', verbose_name='Classificazione')),
                ('service_types', models.ManyToManyField(help_text='Servizi inclusi nel set', related_name='service_sets', to='vendors.servicetype', verbose_name='Servizi')),
            ],
            options={
                'verbose_name': 'Set Servizi',
                'verbose_name_plural': 'Set Servizi',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
