# Generated by Django 5.0.6 on 2026-09-15 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0035_competenceset_serviceset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Classificazione', 'verbose_name_plural': 'Classificazioni'},
        ),
        migrations.AddField(
            model_name='vendor',
            name='albo_excel_row',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text="Numero di riga del foglio Excel dell'Albo Fornitori da cui il fornitore è stato importato (l'intestazione è la riga 1)", null=True, verbose_name='Riga excel Albo Fornitore'),
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(help_text="Codice univoco della classificazione (es. 'SERV', 'FORN', 'MANU')", max_length=20, unique=True, verbose_name='Codice Classificazione'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Descrizione dettagliata della classificazione', null=True, verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Classificazione attiva e utilizzabile', verbose_name='È Attiva'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Nome della classificazione', max_length=100, verbose_name='Nome Classificazione'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Classificazione padre per struttura gerarchica', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='vendors.category', verbose_name='Classificazione Padre'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='competence_category',
            field=models.CharField(choices=[('SAFETY', 'Sicurezza'), ('QUALITY', 'Qualità'), ('TECHNICAL', 'Tecnico'), ('ENERGY', 'Energia'), ('ENVIRONMENT', 'Ambiente'), ('DOCTOR', 'Medico/Infermieristico'), ('AUDIT', 'Audit/Certificazioni'), ('OTHER', 'Altro')], default='TECHNICAL', help_text='Categoria del requisito professionale', max_length=50, verbose_name='Categoria Requisito Professionale'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('ACCORDO_QUADRO', 'Accordo quadro'), ('ORDINE', 'Ordine'), ('ORDINE_RICORRENTE', 'Ordine ricorrente'), ('DEROGA', 'Deroga'), ('FORNITURA_OCCASIONALE', 'Fornitura occasionale')], help_text='Tipologia del contratto', max_length=30, null=True, verbose_name='Tipo contratto'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Categoria merceologica del fornitore', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='vendors.category', verbose_name='Classificazione'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_type',
            field=models.CharField(blank=True, choices=[('Società', 'Società'), ('Professionista', 'Professionista'), ('Dipendente', 'Dipendente'), ('Dipendente + Libero professionista', 'Dipendente + Libero professionista'), ('Disoccupato', 'Disoccupato'), ('Libero Professionista', 'Libero Professionista'), ('Presso Studio', 'Presso Studio'), ('Prestazione Occasionale', 'Prestazione Occasionale'), ('Società/professionista', 'Società/professionista'), ('Subappaltatore', 'Subappaltatore'), ('Internazionale', 'Internazionale')], default='Società', help_text='Tipo di fornitore', max_length=50, null=True, verbose_name='Tipo di Fornitore'),
        ),
    ]
