# Generated by Django 5.0.6 on 2026-09-16 14:04


import django.db.models.deletion
from django.db import migrations, models

import vendor_management_system.vendors.models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0037_vendor_embyon_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorOperationalAttributes",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=vendor_management_system.vendors.models.generate_operational_attributes_id,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_operators",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Numero totale di operatori disponibili",
                        null=True,
                        verbose_name="Numero Totale Operatori",
                    ),
                ),
                (
                    "equipped_vans",
                    models.BooleanField(
                        default=False,
                        verbose_name="Furgoni attrezzati (carrofficina)",
                    ),
                ),
                (
                    "aerial_platforms",
                    models.BooleanField(
                        default=False, verbose_name="Piattaforme - PLE"
                    ),
                ),
                (
                    "aerial_platforms_notes",
                    models.TextField(
                        blank=True,
                        help_text="Tipologia, altezza, portata",
                        null=True,
                        verbose_name="Note Piattaforme - PLE",
                    ),
                ),
                (
                    "mobile_scaffolding",
                    models.BooleanField(
                        default=False, verbose_name="Ponteggio mobile"
                    ),
                ),
                (
                    "mobile_scaffolding_notes",
                    models.TextField(
                        blank=True,
                        help_text="Tipologia, altezza",
                        null=True,
                        verbose_name="Note Ponteggio mobile",
                    ),
                ),
                (
                    "equipped_vehicle_for_inspections",
                    models.BooleanField(
                        default=False,
                        verbose_name=(
                            "Mezzo attrezzato (per revisione e collaudi "
                            "sul posto)"
                        ),
                    ),
                ),
                (
                    "lifting_equipment",
                    models.BooleanField(
                        default=False,
                        verbose_name=(
                            "Mezzi di sollevamento (camion gru/carrello "
                            "elevatore)"
                        ),
                    ),
                ),
                (
                    "lifting_equipment_notes",
                    models.TextField(
                        blank=True,
                        help_text="Tipologia, altezza, portata",
                        null=True,
                        verbose_name="Note Mezzi di sollevamento",
                    ),
                ),
                (
                    "atex_equipment",
                    models.BooleanField(
                        default=False, verbose_name="Strumentazione ATEX"
                    ),
                ),
                (
                    "standard_hourly_labor_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Costo Orario Standard Manodopera (€)",
                    ),
                ),
                (
                    "travel_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Costo Trasferta (€)",
                    ),
                ),
                (
                    "mileage_reimbursement",
                    models.BooleanField(
                        default=False, verbose_name="Rimborso Chilometrico"
                    ),
                ),
                (
                    "mileage_reimbursement_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valore Rimborso Chilometrico (€/km)",
                    ),
                ),
                (
                    "consumable_materials_supply",
                    models.BooleanField(
                        default=False,
                        verbose_name=(
                            "Fornitura Materiali di consumo (tubo, cavo…)"
                        ),
                    ),
                ),
                (
                    "specialist_materials_supply",
                    models.BooleanField(
                        default=False,
                        verbose_name="Fornitura materiale specialistico",
                    ),
                ),
                (
                    "site_survey_availability",
                    models.BooleanField(
                        default=False,
                        verbose_name="Disponibilità Sopralluoghi per Sicura",
                    ),
                ),
                (
                    "travel_availability",
                    models.BooleanField(
                        default=False, verbose_name="Disponibilità Trasferte"
                    ),
                ),
                (
                    "weekend_holiday_shutdown_availability",
                    models.BooleanField(
                        default=False,
                        verbose_name=(
                            "Disponibilità attività in fermata impianto "
                            "/ weekend/festivi"
                        ),
                    ),
                ),
                (
                    "night_shutdown_availability",
                    models.BooleanField(
                        default=False,
                        verbose_name=(
                            "Disponibilità attività in fermata impianto "
                            "/ notturno"
                        ),
                    ),
                ),
                (
                    "commissioning_support_availability",
                    models.BooleanField(
                        default=False,
                        verbose_name=(
                            "Disponibilità supporto commissioning / collaudi"
                        ),
                    ),
                ),
                (
                    "autonomy_category",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (
                                1,
                                "Solo Manodopera (serve capocantiere + "
                                "PM Sicura)",
                            ),
                            (2, "Autonomia limitata (serve PM Sicura)"),
                            (3, "Totale autonomia"),
                        ],
                        null=True,
                        verbose_name="Categoria Autonomia",
                    ),
                ),
                (
                    "experience_logistics",
                    models.BooleanField(
                        default=False, verbose_name="Logistica"
                    ),
                ),
                (
                    "experience_data_center",
                    models.BooleanField(
                        default=False, verbose_name="Data center"
                    ),
                ),
                (
                    "experience_industry_manufacturing",
                    models.BooleanField(
                        default=False, verbose_name="Industria/manufatturiero"
                    ),
                ),
                (
                    "experience_tertiary_offices_hospitality",
                    models.BooleanField(
                        default=False,
                        verbose_name="Terziario/uffici/alberghiero",
                    ),
                ),
                (
                    "experience_food_pharma",
                    models.BooleanField(
                        default=False, verbose_name="Alimentare/farmaceutico"
                    ),
                ),
                (
                    "experience_healthcare",
                    models.BooleanField(
                        default=False, verbose_name="Ospedaliero"
                    ),
                ),
                (
                    "experience_retail",
                    models.BooleanField(default=False, verbose_name="Retail"),
                ),
                (
                    "experience_oil_gas",
                    models.BooleanField(
                        default=False, verbose_name="Oil & Gas"
                    ),
                ),
                (
                    "experience_public_administration",
                    models.BooleanField(
                        default=False, verbose_name="Pubblica Amministrazione"
                    ),
                ),
                (
                    "vendor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operational_attributes",
                        to="vendors.vendor",
                        verbose_name="Fornitore",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attributi Operativi",
                "verbose_name_plural": "Attributi Operativi",
            },
        ),
    ]
