# Generated by Django 5.0.6 on 2026-09-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0038_vendoroperationalattributes"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="first_supply_date",
            field=models.DateField(
                blank=True,
                help_text=(
                    "Data del primo servizio di fornitura erogato dal "
                    "fornitore"
                ),
                null=True,
                verbose_name="Data Prima Fornitura",
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="pec",
            field=models.EmailField(
                blank=True,
                help_text="Posta Elettronica Certificata",
                max_length=254,
                null=True,
                verbose_name="PEC",
            ),
        ),
    ]
