# Generated by Django 6.0.8 on 2026-09-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0041_seed_geography"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="competence_countries",
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "Nazioni senza articolazione in regioni/province a "
                    "catalogo, selezionabili solo a livello nazione. "
                    "L'Italia non va mai qui: la sua copertura si "
                    "esprime con le province."
                ),
                related_name="competent_vendors",
                to="vendors.country",
                verbose_name="Nazioni estere di competenza",
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="competence_provinces",
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "Province italiane in cui il fornitore opera. La "
                    "copertura di una regione è derivata: risulta "
                    "selezionata quando lo sono tutte le sue province."
                ),
                related_name="competent_vendors",
                to="vendors.province",
                verbose_name="Province di competenza",
            ),
        ),
    ]
