# Generated by Django 6.0.8 on 2026-09-23 16:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0043_migrate_competence_zones"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competencezonerule",
            name="zone",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="competence_zones",
        ),
        migrations.RemoveField(
            model_name="competencezonerule",
            name="country",
        ),
        migrations.RemoveField(
            model_name="competencezonerule",
            name="province",
        ),
        migrations.RemoveField(
            model_name="competencezonerule",
            name="region",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="competences_zone",
        ),
        migrations.DeleteModel(
            name="CompetenceZone",
        ),
        migrations.DeleteModel(
            name="CompetenceZoneRule",
        ),
    ]
