# Generated by Django 5.0.6 on 2026-09-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0044_remove_competence_zone_stack"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="competence",
            options={
                "ordering": ["competence_category", "sort_order", "name"],
                "verbose_name": "Abilitazione/Requisito Professionale",
                "verbose_name_plural": (
                    "Catalogo Abilitazioni e Requisiti Professionali"
                ),
            },
        ),
        migrations.AlterModelOptions(
            name="competenceset",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": ("Set Abilitazioni e Requisiti Professionali"),
                "verbose_name_plural": (
                    "Set Abilitazioni e Requisiti Professionali"
                ),
            },
        ),
        migrations.AlterModelOptions(
            name="serviceset",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "Set Servizi Erogati",
                "verbose_name_plural": "Set Servizi Erogati",
            },
        ),
        migrations.AlterModelOptions(
            name="servicetype",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "Tipo/Servizio Erogato",
                "verbose_name_plural": "Tipologie e Servizi Erogati",
            },
        ),
        migrations.AlterModelOptions(
            name="vendorcompetence",
            options={
                "ordering": ["-created_at"],
                "verbose_name": (
                    "Abilitazione/Requisito Professionale Assegnato"
                ),
                "verbose_name_plural": (
                    "Abilitazioni e Requisiti Professionali Assegnati"
                ),
            },
        ),
        migrations.AlterModelOptions(
            name="vendorservice",
            options={
                "ordering": ["-is_primary", "-created_at"],
                "verbose_name": "Servizio Erogato",
                "verbose_name_plural": "Servizi Erogati",
            },
        ),
        migrations.AlterField(
            model_name="competenceset",
            name="competences",
            field=models.ManyToManyField(
                help_text=(
                    "Abilitazioni e requisiti professionali inclusi nel set"
                ),
                related_name="competence_sets",
                to="vendors.competence",
                verbose_name="Abilitazioni e Requisiti Professionali",
            ),
        ),
        migrations.AlterField(
            model_name="serviceset",
            name="service_types",
            field=models.ManyToManyField(
                help_text="Servizi erogati inclusi nel set",
                related_name="service_sets",
                to="vendors.servicetype",
                verbose_name="Servizi Erogati",
            ),
        ),
    ]
