# Generated by Django 5.0.6 on 2026-09-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "vendors",
            "0045_alter_competence_options_alter_competenceset_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="embyon_company",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CmaSrl", "CmaSrl"),
                    ("Evimed", "Evimed"),
                    ("GsProtec", "GsProtec"),
                    ("Igeam", "Igeam"),
                    ("Sicura", "Sicura"),
                ],
                help_text=(
                    "Società Embyon (DITTA) presso cui il fornitore è censito"
                ),
                max_length=50,
                null=True,
                verbose_name="Società Embyon",
            ),
        ),
    ]
