# Generated by Django 5.0.6 on 2026-09-29 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0046_alter_vendor_embyon_company"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="additional_categories",
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "Ulteriori classificazioni del fornitore, "
                    "oltre a quella principale (opzionali)"
                ),
                related_name="additional_vendors",
                to="vendors.category",
                verbose_name="Classificazioni aggiuntive",
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="secondary_managers",
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "Ulteriori utenti Back Office o Admin "
                    "di riferimento per il fornitore (opzionali)"
                ),
                limit_choices_to={"role__in": ["admin", "bo_user"]},
                related_name="secondary_managed_vendors",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utenti gestione fornitore secondari",
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Classificazione principale del fornitore",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendors",
                to="vendors.category",
                verbose_name="Classificazione",
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="managed_by",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Utente Back Office o Admin responsabile "
                    "della gestione del fornitore (utente primario)"
                ),
                limit_choices_to={"role__in": ["admin", "bo_user"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_vendors",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utenti gestione fornitore",
            ),
        ),
    ]
