# Generated by Django 5.0.6 on 2026-10-01 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0047_vendor_secondary_managers_additional_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="expiry_notifications_enabled",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Invia all'email principale i promemoria di scadenza di "
                    "documenti e abilitazioni. Senza email il promemoria non "
                    "parte."
                ),
                verbose_name="Notifiche scadenze via email",
            ),
        ),
        migrations.CreateModel(
            name="ExpiryReminderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_kind",
                    models.CharField(
                        choices=[
                            ("DOCUMENT", "Documento"),
                            ("COMPETENCE", "Abilitazione/Requisito"),
                        ],
                        max_length=20,
                        verbose_name="Tipo elemento",
                    ),
                ),
                (
                    "item_id",
                    models.CharField(
                        max_length=64, verbose_name="ID elemento"
                    ),
                ),
                (
                    "item_label",
                    models.CharField(max_length=255, verbose_name="Elemento"),
                ),
                (
                    "expiry_date",
                    models.DateField(verbose_name="Data scadenza"),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("FIRST", "Primo promemoria"),
                            ("SECOND", "Ultimo avviso (7 giorni)"),
                        ],
                        max_length=10,
                        verbose_name="Stadio",
                    ),
                ),
                (
                    "recipients",
                    models.CharField(
                        max_length=500, verbose_name="Destinatari"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Inviato il"
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expiry_reminders",
                        to="vendors.vendor",
                        verbose_name="Fornitore",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promemoria scadenza inviato",
                "verbose_name_plural": "Promemoria scadenze inviati",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="expiryreminderlog",
            constraint=models.UniqueConstraint(
                fields=("item_kind", "item_id", "expiry_date", "stage"),
                name="unique_expiry_reminder_per_stage",
            ),
        ),
    ]
