# Generated by Django 6.0.8 on 2026-10-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0049_competence_validity_days_reminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorcompetence",
            name="pending_certification_number",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Nuova versione: numero certificazione",
            ),
        ),
        migrations.AddField(
            model_name="vendorcompetence",
            name="pending_document_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="vendor_competences/pending/%Y/%m/",
                verbose_name="Nuova versione: file",
            ),
        ),
        migrations.AddField(
            model_name="vendorcompetence",
            name="pending_expiry_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Nuova versione: data scadenza",
            ),
        ),
        migrations.AddField(
            model_name="vendorcompetence",
            name="pending_issue_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Nuova versione: data rilascio",
            ),
        ),
        migrations.AddField(
            model_name="vendorcompetence",
            name="pending_notes",
            field=models.TextField(
                blank=True, verbose_name="Nuova versione: note"
            ),
        ),
        migrations.AddField(
            model_name="vendorcompetence",
            name="pending_uploaded_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Nuova versione: caricata il",
            ),
        ),
    ]
