# Generated by Django 6.0.8 on 2026-10-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0050_revisione_in_attesa"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorcompetence",
            name="rejected",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Documento respinto dal gestore, "
                    "in attesa di un nuovo caricamento"
                ),
                verbose_name="Respinta",
            ),
        ),
    ]
