# Generated by Django 5.0.6 on 2026-10-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0051_vendorcompetence_rejected"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="vendor_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Società", "Società"),
                    ("Professionista", "Professionista"),
                    ("Dipendente", "Dipendente"),
                    (
                        "Dipendente + Libero professionista",
                        "Dipendente + Libero professionista",
                    ),
                    ("Disoccupato", "Disoccupato"),
                    ("Libero Professionista", "Libero Professionista"),
                    ("Presso Studio", "Presso Studio"),
                    ("Prestazione Occasionale", "Prestazione Occasionale"),
                    ("Società/professionista", "Società/professionista"),
                    ("Subappaltatore", "Subappaltatore"),
                    ("Internazionale", "Internazionale"),
                ],
                default="Società",
                help_text="Tipo di fornitore",
                max_length=50,
                null=True,
                verbose_name="Tipo di Fornitore",
            ),
        ),
    ]
