# Generated by Django 6.0.8 on 2026-10-07 15:08

from django.db import migrations, models
from django.db.models import Q


def ricalcola_valutazione_finale(apps, schema_editor):
    """Sostituisce le valutazioni manuali con il bollino calcolato da stato di
    qualifica ed Embyon (stessa regola di Vendor.final_evaluation_for)."""
    Vendor = apps.get_model("vendors", "Vendor")
    negative = Q(embyon_active=False) | Q(qualification_status="REJECTED")
    positive = Q(embyon_active=True, qualification_status="APPROVED")
    Vendor.objects.filter(negative).update(vendor_final_evaluation="NEGATIVO")
    Vendor.objects.filter(positive).update(vendor_final_evaluation="POSITIVO")
    Vendor.objects.exclude(negative | positive).update(
        vendor_final_evaluation="DA VALUTARE"
    )


class Migration(migrations.Migration):
    dependencies = [
        (
            "vendors",
            "0052_rimuovi_tipi_fornitore_formatore_consulente_laboratorio",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="vendor_final_evaluation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DA VALUTARE", "Da Valutare"),
                    ("NEGATIVO", "Negativo"),
                    ("POSITIVO", "Positivo"),
                ],
                default="DA VALUTARE",
                editable=False,
                help_text=(
                    "Calcolata in automatico: Positivo se Approvato e attivo "
                    "in Embyon, Negativo se Respinto o non attivo in Embyon, "
                    "altrimenti Da Valutare"
                ),
                max_length=20,
                null=True,
                verbose_name="Valutazione Finale del Fornitore",
            ),
        ),
        # Le vecchie valutazioni manuali non sono ricostruibili.
        migrations.RunPython(
            ricalcola_valutazione_finale, migrations.RunPython.noop
        ),
    ]
