# Generated by Django 5.0.6 on 2025-10-16 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.CharField(editable=False, help_text='Unique ID for Document Type', max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Document Type ID')),
                ('name', models.CharField(help_text='Name of document type (e.g. DURC, ISO 9001, etc.)', max_length=100, verbose_name='Document Type Name')),
                ('description', models.TextField(blank=True, help_text='Description of this document type', verbose_name='Description')),
                ('is_required', models.BooleanField(default=True, help_text='Whether this document is required for vendor qualification', verbose_name='Required')),
                ('validity_period_days', models.IntegerField(default=365, help_text='How many days this document is valid for', verbose_name='Validity Period (Days)')),
                ('reminder_days_before', models.IntegerField(default=30, help_text='Send reminder X days before expiry', verbose_name='Reminder Days Before Expiry')),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(editable=False, help_text='Unique ID for Document', max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Document ID')),
                ('file', models.FileField(blank=True, help_text='Upload the document file', null=True, upload_to='vendor_documents/%Y/%m/', verbose_name='Document File')),
                ('issue_date', models.DateField(blank=True, help_text='Date when document was issued', null=True, verbose_name='Issue Date')),
                ('expiry_date', models.DateField(blank=True, help_text='Date when document expires', null=True, verbose_name='Expiry Date')),
                ('status', models.CharField(choices=[('PENDING', 'In attesa di caricamento'), ('UPLOADED', 'Caricato - da verificare'), ('APPROVED', 'Approvato'), ('REJECTED', 'Respinto'), ('EXPIRED', 'Scaduto')], default='PENDING', help_text='Current status of document', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this document', verbose_name='Notes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When document was uploaded', verbose_name='Uploaded At')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When document was reviewed', null=True, verbose_name='Reviewed At')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='User who reviewed this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('vendor', models.ForeignKey(help_text='Vendor who owns this document', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vendors.vendor', verbose_name='Vendor')),
                ('document_type', models.ForeignKey(help_text='Type of document', on_delete=django.db.models.deletion.CASCADE, to='documents.documenttype', verbose_name='Document Type')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
                'unique_together': {('vendor', 'document_type')},
            },
        ),
    ]
