# Generated by Django 5.0.6 on 2025-11-18 14:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('vendors', '0016_remove_vendordocument_document_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['document_category', 'sort_order', 'name'], 'verbose_name': 'Document Type', 'verbose_name_plural': 'Document Types'},
        ),
        migrations.AddField(
            model_name='documenttype',
            name='applicable_categories',
            field=models.ManyToManyField(blank=True, help_text='Categorie per cui questo documento è richiesto', related_name='required_documents', to='vendors.category', verbose_name='Categorie Applicabili'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='code',
            field=models.CharField(blank=True, help_text="Codice univoco del tipo di documento (es. 'DURC', 'VISURA')", max_length=50, null=True, unique=True, verbose_name='Codice Documento'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creato il'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='document_category',
            field=models.CharField(blank=True, choices=[('LEGAL', 'Legale/Amministrativo'), ('FINANCIAL', 'Finanziario'), ('SAFETY', 'Sicurezza'), ('QUALITY', 'Qualità'), ('TECHNICAL', 'Tecnico'), ('INSURANCE', 'Assicurativo'), ('CERTIFICATION', 'Certificazioni'), ('OTHER', 'Altro')], default='LEGAL', help_text='Categoria del documento', max_length=50, null=True, verbose_name='Categoria Documento'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='instructions',
            field=models.TextField(blank=True, help_text='Istruzioni per il fornitore su come compilare/ottenere il documento', null=True, verbose_name='Istruzioni'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Tipo di documento attivo e utilizzabile', verbose_name='È Attivo'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='requires_renewal',
            field=models.BooleanField(default=True, help_text='Documento con scadenza che necessita rinnovo', verbose_name='Richiede Rinnovo'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='sort_order',
            field=models.PositiveIntegerField(default=100, help_text='Ordine di visualizzazione', verbose_name='Ordine di Ordinamento'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='template_file',
            field=models.FileField(blank=True, help_text='Template o modello del documento', null=True, upload_to='document_templates/', verbose_name='File Template'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aggiornato il'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this document type', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.CharField(help_text='Name of document type (e.g. DURC, ISO 9001, etc.)', max_length=255, verbose_name='Document Type Name'),
        ),
        migrations.AddIndex(
            model_name='documenttype',
            index=models.Index(fields=['code'], name='documents_d_code_abe763_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttype',
            index=models.Index(fields=['document_category', 'is_active'], name='documents_d_documen_9c6fde_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttype',
            index=models.Index(fields=['is_required'], name='documents_d_is_requ_5b4a7c_idx'),
        ),
    ]
