# Generated by Django 5.0.6 on 2025-11-18 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_documenttype_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documenti'},
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(help_text='Tipo di documento', on_delete=django.db.models.deletion.CASCADE, to='documents.documenttype', verbose_name='Tipo di Documento'),
        ),
        migrations.AlterField(
            model_name='document',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Data di scadenza del documento', null=True, verbose_name='Data di Scadenza'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, help_text='Carica il file del documento', null=True, upload_to='vendor_documents/%Y/%m/', verbose_name='File Documento'),
        ),
        migrations.AlterField(
            model_name='document',
            name='issue_date',
            field=models.DateField(blank=True, help_text='Data di emissione del documento', null=True, verbose_name='Data di Emissione'),
        ),
        migrations.AlterField(
            model_name='document',
            name='notes',
            field=models.TextField(blank=True, help_text='Note aggiuntive su questo documento', verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='document',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Utente che ha revisionato questo documento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL, verbose_name='Revisionato da'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('PENDING', 'In attesa di caricamento'), ('UPLOADED', 'Caricato - da verificare'), ('APPROVED', 'Approvato'), ('REJECTED', 'Respinto'), ('EXPIRED', 'Scaduto')], default='PENDING', help_text='Stato corrente del documento', max_length=20, verbose_name='Stato'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data di caricamento del documento', verbose_name='Data di Caricamento'),
        ),
    ]
