# Generated by Django 5.0.6 on 2026-06-10 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_documenttype_options'),
        ('vendors', '0034_rename_embyon_blocked_embyon_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nome del set documentale (es. 'Set base appalti', 'Set sanitario')", max_length=255, verbose_name='Nome Set')),
                ('description', models.TextField(blank=True, help_text='Descrizione del set documentale', null=True, verbose_name='Descrizione')),
                ('default_status', models.CharField(choices=[('PENDING', 'In attesa di caricamento'), ('UPLOADED', 'Caricato - da verificare'), ('APPROVED', 'Approvato'), ('REJECTED', 'Respinto'), ('EXPIRED', 'Scaduto')], default='PENDING', help_text='Stato applicato ai documenti creati dal set', max_length=20, verbose_name='Stato Predefinito')),
                ('is_active', models.BooleanField(default=True, help_text='Set attivo e selezionabile', verbose_name='Attivo')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Ordine di visualizzazione', verbose_name='Ordine')),
                ('category', models.ForeignKey(blank=True, help_text='Classificazione del fornitore a cui si applica il set (vuoto = applicabile a tutte le classificazioni)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_sets', to='vendors.category', verbose_name='Classificazione')),
                ('document_types', models.ManyToManyField(help_text='Tipi di documento inclusi nel set', related_name='document_sets', to='documents.documenttype', verbose_name='Tipi di Documento')),
            ],
            options={
                'verbose_name': 'Set Documentale',
                'verbose_name_plural': 'Set Documentali',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
