# Generated by Django 5.0.6 on 2026-09-24 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0008_fix_documentset_id_pk"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "Documento Contrattuale",
                "verbose_name_plural": "Registro Documenti Contrattuali",
            },
        ),
        migrations.AlterModelOptions(
            name="documentcatalog",
            options={
                "ordering": ["document_category", "sort_order", "name"],
                "verbose_name": "Tipo di Documento Contrattuale",
                "verbose_name_plural": "Catalogo Documenti Contrattuali",
            },
        ),
    ]
