# Generated by Django 5.0.6 on 2026-09-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "documents",
            "0009_alter_document_options_alter_documentcatalog_options",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentcatalog",
            name="is_required",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Whether this document is required for vendor "
                    "qualification"
                ),
                verbose_name="È obbligatorio",
            ),
        ),
    ]
