# Generated by Django 5.0.6 on 2026-10-01 08:36

import django.core.validators
from django.db import migrations, models

REMINDER_DAYS_DEFAULT = 30
REMINDER_DAYS_MIN = 10
REMINDER_DAYS_MAX = 90


def align_reminder_days(apps, schema_editor):
    """Tipi senza rinnovo: nessun preavviso. Tipi con rinnovo: valore nel
    range del validator (o il default se mancante), così l'admin li salva."""
    DocumentCatalog = apps.get_model("documents", "DocumentCatalog")
    DocumentCatalog.objects.filter(requires_renewal=False).update(
        reminder_days_before=None
    )
    renewable = DocumentCatalog.objects.filter(requires_renewal=True)
    renewable.filter(reminder_days_before__isnull=True).update(
        reminder_days_before=REMINDER_DAYS_DEFAULT
    )
    renewable.filter(reminder_days_before__lt=REMINDER_DAYS_MIN).update(
        reminder_days_before=REMINDER_DAYS_MIN
    )
    renewable.filter(reminder_days_before__gt=REMINDER_DAYS_MAX).update(
        reminder_days_before=REMINDER_DAYS_MAX
    )


def restore_not_null(apps, schema_editor):
    # Il campo torna NOT NULL: 0 era il valore dei tipi senza rinnovo.
    DocumentCatalog = apps.get_model("documents", "DocumentCatalog")
    DocumentCatalog.objects.filter(reminder_days_before__isnull=True).update(
        reminder_days_before=0
    )


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0010_label_documentcatalog_is_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentcatalog",
            name="reminder_days_before",
            field=models.IntegerField(
                blank=True,
                default=30,
                help_text=(
                    "Solo per i documenti che richiedono rinnovo (tra 10 e "
                    "90): giorni prima della scadenza in cui il documento "
                    "passa a EXPIRING_SOON e parte il primo promemoria email "
                    "al fornitore. Il secondo promemoria parte sempre a 7 "
                    "giorni."
                ),
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(90),
                ],
                verbose_name="Giorni di preavviso scadenza",
            ),
        ),
        migrations.RunPython(align_reminder_days, restore_not_null),
    ]
