# Generated by Django 5.0.6 on 2025-10-15 20:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('po_number', models.CharField(editable=False, help_text='Unique Purchase Order Number', max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Purchase Order Number must be uppercase alphanumeric', regex='^[A-Z0-9]+$')], verbose_name='Purchase Order Number')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date of Purchase Order', verbose_name='Order Date')),
                ('expected_delivery_date', models.DateTimeField(blank=True, help_text='Expected Date of Delivery', null=True, verbose_name='Expected Delivery Date')),
                ('actual_delivery_date', models.DateTimeField(blank=True, help_text='Actual Date of Delivery', null=True, verbose_name='Actual Delivery Date')),
                ('items', models.JSONField(help_text='Items in Purchase Order', verbose_name='Items')),
                ('quantity', models.IntegerField(help_text='Total Quantity in Purchase Order', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ISSUED', 'Issued'), ('ACKNOWLEDGED', 'Acknowledged'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Status of Purchase Order', max_length=20, verbose_name='Status')),
                ('quality_rating', models.FloatField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Quality Rating of Purchase Order', max_length=1, null=True, verbose_name='Quality Rating')),
                ('issue_date', models.DateTimeField(blank=True, help_text='Date of Issue', null=True, verbose_name='Issue Date')),
                ('acknowledgment_date', models.DateTimeField(blank=True, help_text='Date of Acknowledgment', null=True, verbose_name='Acknowledgment Date')),
                ('vendor', models.ForeignKey(blank=True, help_text='Vendor associated with Purchase Order', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['order_date'],
            },
        ),
    ]
