# Generated by Django 5.0.6 on 2026-05-07 11:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0031_vendor_embyon_blocked_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changes', models.JSONField(default=dict, help_text="Mappa {campo: {'old': valore_attuale, 'new': valore_proposto}}", verbose_name='Modifiche proposte')),
                ('status', models.CharField(choices=[('PENDING', 'In attesa'), ('APPROVED', 'Approvata'), ('REJECTED', 'Respinta')], default='PENDING', max_length=20, verbose_name='Stato')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creata il')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Revisionata il')),
                ('review_notes', models.TextField(blank=True, verbose_name='Note di revisione')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='Richiesto da')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_vendor_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='Revisionata da')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='vendors.vendor', verbose_name='Fornitore')),
            ],
            options={
                'verbose_name': 'Richiesta modifica anagrafica',
                'verbose_name_plural': 'Richieste modifica anagrafica',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', 'status'], name='portal_vend_vendor__1650f6_idx'), models.Index(fields=['status', 'created_at'], name='portal_vend_status_539295_idx')],
            },
        ),
    ]
