# Generated by Django 6.0.8 on 2026-09-16 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0001_initial"),
        ("vendors", "0038_vendoroperationalattributes"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorchangerequest",
            name="vendor_service",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Se valorizzato, le modifiche si applicano a questo "
                    "servizio invece che all'anagrafica del fornitore."
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="change_requests",
                to="vendors.vendorservice",
                verbose_name="Servizio fornitore",
            ),
        ),
    ]
