# Generated by Django 5.0.6 on 2026-09-22 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0002_vendorchangerequest_vendor_service"),
        ("vendors", "0039_vendor_first_supply_date_vendor_pec"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorchangerequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("EDIT", "Modifica"),
                    ("ADD_SERVICE", "Aggiunta servizio"),
                    ("DELETE_SERVICE", "Eliminazione servizio"),
                ],
                default="EDIT",
                max_length=20,
                verbose_name="Tipo richiesta",
            ),
        ),
        migrations.AddField(
            model_name="vendorchangerequest",
            name="service_type",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Valorizzato solo per le richieste di aggiunta "
                    "(ADD_SERVICE): il servizio del catalogo che il "
                    "fornitore propone di erogare, non ancora esistente "
                    "come VendorService."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="add_requests",
                to="vendors.servicetype",
                verbose_name="Servizio richiesto",
            ),
        ),
        migrations.AlterField(
            model_name="vendorchangerequest",
            name="vendor_service",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Se valorizzato, le modifiche si applicano a questo "
                    "servizio invece che all'anagrafica del fornitore. "
                    "Per le richieste di eliminazione (DELETE_SERVICE) "
                    "viene azzerato all'approvazione, prima della "
                    "cancellazione del servizio, così da non perdere lo "
                    "storico della richiesta."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="change_requests",
                to="vendors.vendorservice",
                verbose_name="Servizio fornitore",
            ),
        ),
    ]
